---

- hosts: raspberries
  name: Init rapsberries
  gather_facts: false
  vars:
    default_password: "ubuntu"
  vars_prompt:
    - name: password
      prompt: What is your password?
  tasks:
    - name: "Check if host is reachable"
      wait_for:
        timeout: 0
      register: connect_rs
      ignore_unreachable: yes

    - when: connect_rs is unreachable
      name: "Try first login and change the password"
      delegate_to: localhost
      expect:
        command: sshpass -p {{ default_password }} ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }}
        timeout: 10
        responses:
          "Current password:": "{{ default_password }}"
          "New password:": "{{ password }}"
          "Retype new password:": "{{ password }}"

    - when: connect_rs is unreachable
      name: "Change ssh password"
      set_fact:
        ansible_password: "{{ password }}"

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      become: yes
      notify: reboot

    - name: Add my ssh key
      authorized_key:
        user: ubuntu
        key: https://github.com/kilbiller.keys
      notify: restart ssh

    - name: Disable poe hat fan
      blockinfile:
        block: "{{ lookup('file', './init/usercfg.txt') }}"
        path: /boot/firmware/usercfg.txt
        create: yes
      become: yes
      notify: reboot

    - name: Disable password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        validate: /usr/sbin/sshd -T -f %s
      become: yes
      notify: restart ssh

    - name: Disable root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        validate: /usr/sbin/sshd -T -f %s
      become: yes
      notify: restart ssh

  handlers:
    - name: reboot
      reboot:
      become: yes
    - name: restart ssh
      service:
        name: sshd
        state: restarted
      become: yes
