---

- hosts: raspberries
  name: Init rapsberries
  gather_facts: false
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      become: yes
      notify: reboot

    - name: Add my ssh key
      authorized_key:
        user: ubuntu
        key: https://github.com/kilbiller.keys
      notify: restart ssh

    - name: Disable poe hat fan
      blockinfile:
        block: "{{ lookup('file', './init/usercfg.txt') }}"
        path: /boot/firmware/usercfg.txt
        create: yes
      become: yes
      notify: reboot

    - name: Enable some cgroup for kubernetes
      replace:
        path: /boot/firmware/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      loop:
        - "cgroup_enable=cpuset"
        - "cgroup_memory=1"
        - "cgroup_enable=memory"
      become: yes
      notify: reboot

    - name: Disable password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        validate: /usr/sbin/sshd -T -f %s
      become: yes
      notify: restart ssh

    - name: Disable root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        validate: /usr/sbin/sshd -T -f %s
      become: yes
      notify: restart ssh

    - name: Allow & Limit port 22
      community.general.ufw:
        rule: limit
        direction: in
        proto: tcp
        port: "22"
      become: yes

    - name: Allow port 80
      community.general.ufw:
        rule: allow
        direction: in
        proto: tcp
        port: "80"
      become: yes

    - name: Allow port 443
      community.general.ufw:
        rule: allow
        direction: in
        proto: tcp
        port: "443"
      become: yes

    - name: Allow requests from home network
      community.general.ufw:
        rule: allow
        direction: in
        from: "192.168.1.0/24"
      become: yes

    - name: Allow routed requests by default
      community.general.ufw:
        default: allow
        direction: routed
      become: yes

    - name: Enable ufw
      community.general.ufw:
        state: enabled
      become: yes

  handlers:
    - name: reboot
      reboot:
      become: yes
    - name: restart ssh
      service:
        name: sshd
        state: restarted
      become: yes
